# Site settings
email: "ridwan.arefin@gmail.com"
baseurl: "https://kaziridwan.github.io/blog"
paginate: 5
paginate_path: "/posts/page-:num"
google_analytics: 

# SEO settings
title: Kazi's Blog
description: Kazi Ridwan's technical and often personal blog.
url: "https://kaziridwan.github.io/blog"
twitter_username: ridwanshere
default_img: 

# Profile settings
name: Kazi Ridwan
profile_img: https://kaziridwan.github.io/storage/uploads/2015/01/Swayze-cover_bw.jpg
profile: 
social:
  github: https://github.com/kaziridwan

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
